---
name: Publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Video Puppet
        uses: videopuppet/build-video-github-action@v1.0.0
        id: video
        with:
          source-path: video.md
          github-token: ${{ secrets.GITHUB_TOKEN }}
          videopuppet-api-key: ${{ secrets.VIDEOPUPPET_API_KEY }}
      - uses: actions/upload-artifact@v1
        with:
          name: video
          path: "${{ steps.video.outputs.video-file }}"
